"""Add order_num and is_active to question

Revision ID: fd6b09e0e299
Revises: 4323820566e2
Create Date: 2024-03-12 14:44:27.550288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd6b09e0e299"
down_revision = "4323820566e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_num", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.drop_column("is_active")
        batch_op.drop_column("order_num")

    # ### end Alembic commands ###
