"""empty message

Revision ID: 878bde435efd
Revises: 364d866d9abe
Create Date: 2024-05-04 20:00:18.863554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878bde435efd'
down_revision = '364d866d9abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
